from typing import Literal

from pydantic import BaseModel, Field


class Decision(BaseModel):
    """The LLM's structured decision output (paper section 3.3, stage 3:
    Decision) for ONE observed post at a time (roadmap Phase 4, per-post
    redesign). `target_object`/`system_response`/`execution_status`, the
    paper's other Decision fields, are all filled in by the runtime rather
    than generated by the model: `target_object` is derived deterministically
    from whichever single tweet this decision concerns (see
    TwitterScraper._resolve_target), and system_response/execution_status
    only exist after execute_action() actually runs -- asking the model to
    predict its own execution outcome before executing would just invite it
    to hallucinate success.
    """

    trigger_check: str = Field(
        description=(
            "Before choosing an action: check THIS post against your persona's "
            "specific trigger conditions (especially any 'always'/'almost always'/"
            "'quite likely' mute or follow rule). State whether it matches a "
            "trigger, and which one, or 'none' if it doesn't. This must be filled "
            "in before `action` and should determine it, not just justify it "
            "after the fact."
        )
    )
    action: Literal["like", "retweet", "follow", "mute", "no_action"] = Field(
        description="The platform operation to perform on this post, or 'no_action' to do nothing about it."
    )
